# Generated by Django 4.2.5 on 2023-10-03 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_variationmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='Variant_category',
            new_name='variation_category',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='Variant_value',
            new_name='variation_value',
        ),
    ]
