# Generated by Django 4.2.5 on 2023-10-03 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_variant_category_variation_variation_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
