# Generated by Django 4.2.5 on 2023-10-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_delete_variationmanager'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
