# Generated by Django 5.0.1 on 2024-05-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
    ]
